plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.8.10'
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.8.10'
}

group = 'top.spco'
version = '5.0.0'

javadoc {
    failOnError = false
    options.encoding = 'UTF-8'
}

repositories {
    maven { url 'https://maven.aliyun.com/repository/public' }
    maven { url 'https://maven.aliyun.com/repository/central' }
}

dependencies {
    implementation "org.apache.logging.log4j:log4j-core:2.20.0"
    implementation "org.apache.logging.log4j:log4j-api:2.20.0"
    implementation "org.apache.logging.log4j:log4j-slf4j2-impl:2.20.0"
    implementation "org.slf4j:slf4j-api:2.0.7"
    implementation "org.apache.httpcomponents:httpclient:4.5.13"
    implementation "org.apache.httpcomponents:httpcore:4.4.14"

    implementation('com.alibaba:dashscope-sdk-java:2.8.2') {
        exclude group: 'org.slf4j', module: 'slf4j-simple'
    }

    implementation "com.google.zxing:core:3.5.3"
    implementation "com.google.code.gson:gson:2.10.1"
    implementation "com.google.guava:guava:32.0.0-android"
    implementation "org.xerial:sqlite-jdbc:3.42.0.0"
    implementation "org.jetbrains:annotations:24.0.1"
    implementation "org.jsoup:jsoup:1.18.3"

    implementation "com.electronwill.night-config:toml:3.8.1"

    implementation('org.telegram:telegrambots-longpolling:8.2.0') {
        exclude group: 'org.slf4j', module: 'slf4j-simple'
    }
    implementation('org.telegram:telegrambots-client:8.2.0') {
        exclude group: 'org.slf4j', module: 'slf4j-simple'
    }

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.+'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.+'
}

test {
    useJUnitPlatform()
}
